name: untitled
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Versioning for your application
version: 1.0.0+1

# Define the environment SDK
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Add dependencies for PDF generation and sharing
  pdf: ^3.10.3
  printing: ^5.10.0

  # Add dependency for opening links
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets section for images or other files
  assets:
  #- assets/images/

  # Add custom fonts section if needed
  # Example:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
